@startuml
title Bridge ZEC.z to ZEC Communication E
left to right direction

class "ZavaX\nAgent" as ZA
class "Zebra" as Z

ZA -down-> ZA #brown : <color:brown> 31 : Write signature Shares to a block
ZA -down-> ZA #blue : <color:blue> 32 : Aggregate signatures
ZA -down-> ZA #purple : <color:purple> 33 : Sign xfer
ZA -down-> ZA #green : <color:green> 34 : Validation results
ZA -down-> Z : 35 : Submit signed transaction

ZA -down-> Z: 36: Poll for block depth
Z -up-> ZA : 37: Return depth

@enduml