@startuml
title Bridge ZEC.z to ZEC Communication D
left to right direction

class "ZavaX\nAgent" as ZA
class "Signing\nGuardians" as SG

ZA -down-> ZA : 27 : Create new FROST SigningPackage
ZA -down-> SG : 28 : Send SigningPackage to all\n signing guardians participating\nof the signature.
SG -down-> SG : 29 : All t participant signing guardians\nuse SigningPackage, nonces\nand KeyPackage\nto produce their signature round2.sign().
SG -up-> ZA : 30 : All t signing guardians\nsubmit their SignatureShare to ZCE\nthrough authenticated channel

@enduml
