@startuml
title Bridge ZEC.z to ZEC Communication G\nBridging Successful
top to bottom direction

class "ZavaX\nAgent" as ZA
class "ZavaX\nConsensus\nEngine" as ZCE
class "ZEC.z\nContract" as ZC
class "Avalanche\nC-Chain" as CC

ZCE -up-> ZA : **42: Message that ZEC.z can be burnt**
ZA -up-> ZC : 43: Message + gas
ZC -down-> ZC : 44: Verify warp signature\n& weight
ZC -down-> CC : 45: Burn ZEC.z
CC -up-> ZC : 46: Confirmation

@enduml
