@startuml
title Bridge ZEC.z to ZEC Communication F
top to bottom direction

class "ZavaX\nAgent" as ZA
class "ZavaX\nConsensus\nEngine" as ZCE
class "Zebra\n" as Z

ZA -down-> ZCE : **38: Check OK to burn ZEC.z**
ZCE -down-> Z : 39: Transaction committed?
Z -up-> ZCE : 40: Confirmation
ZCE -down-> ZCE : 41: Write block:\ntransaction\nsuccessful/failed

@enduml
