@startuml
left to right direction
title Maintain ZavaX Guardians Communication C\nFROST Distributed Key Generation (DKG) Part 1

class "ZavaX\nAgent" as ZA
class "New/Continuing\nGuardians" as NV

ZA -down-> NV : 10: Run FROST dkg.part1() to generate round1.Package.\nKeeps SecretPackage and broadcast round1.Package\nto the rest of the participants.
NV -down-> NV : 11: Run FROST dkg.part1() to generate round1.Package.\nKeeps SecretPackage and broadcast round1.Package\nto the rest of the participants.
ZA -down-> ZA : 12: Monitor broadcast channel to verify all\nround1. Packages have been broadcasted.
ZA -down-> NV: 13: Gather all broadcasted round1.Package from\nother participants and store in-memory.

@enduml