@startuml

title Maintain ZavaX Guardians and Wallet Control
participant "ZavaX\nAgent" as ZA
entity "Avalanche\nP-Chain" as AP
participant "ZavaX\nConsensus\nEngine" as ZCE
participant "New/Continuing\nGuardians" as NV
participant "Guardian 1" as G1
participant "Current\nGuardians" as PV
participant "Signing\nGuardians" as SG
entity "Zebra" as Z

autonumber
group Preapare for maintenance
    loop
        ZA -> ZA++ : Wait for next\n5 min per 24 hr\ntime slot to become\ncertified Agent
    end
    ZA -> AP++ : New and previously\nabsent ZavaX validators?
    AP --> ZA : List of new ZavaX validators
    ZA -> AP : Expiring ZavaX validators?
    AP --> ZA-- : List of expiring ZavaX validators
end
group Prepare new bridge wallet 
    ZA -> ZCE++ : Make guardians change request\n(certified Agents only)
    ZCE -> ZCE : Verify ZavaX Agent\ncertification & change request
    ZCE -[#red]> ZCE : <color:red>Write block: <b>Status: Down\n'<color:red>ZavaX bridge down for maintenance'
    ZCE -> NV++ : Broadcast create new signature message\nwith total number of n participants and\nt < n threshold number.\n1 key per 0.1% stake.
    G1 -> NV : run FROST dkg.part1 to generate round1.Package.\nKeeps SecretPackage and broadcast round1.Package\nto the rest of the participants
    ZCE -> ZCE : Monitor broadcast channel to verify all\nround1.Packages have been broadcasted 
    G1 -> NV : gather all broadcasted round1.Package from\nother participants and store in-memory\nrun dkg.part2() with own's SecretPackage and broadcast\nround2.Package. Keep\nround2.SecretPackage in memory
    ZCE -> ZCE : Monitor broadcast channel to verify all\nround2.Packages have been broadcasted 
    G1 -> NV : Run dkg.part3() with round2's own's\nSecretPackage all gathered round1.Package\n from part 1 and all round2.Package\n from part 2.
    NV -> NV : Each one stores privately and\nand securely its own KeyPackage with secret key.
    NV --> ZCE-- : Each submit their generated PublicKeyPackage to ZCE.
    ZCE -> ZCE : Check for guardian quorum. 
    ZCE -> ZCE : Aggregate public key\n& wallet address, and\nwrite to a block
    ZCE --> ZA --: New wallet address
end 
group Migrate from current to new bridge wallet
    ZA -> Z ++: Request current wallet balance
    Z --> ZA--: Current wallet balance
    ZA -> ZCE ++: Unsigned xfer transaction\nfrom current to new wallet\n(consolidate UTXOs)\n(certified Agents only)
    ZCE -> ZCE : Verify xfer
    ZCE -> PV : broadcast message to current\nguardians to poll for signing\nguardians\participants.
    ZCE -> SG : Gather FROST commitments\n from signing guardians/participants
    SG --> ZCE : Each submit FROST round1.commit()\nthrough authenticated channel
    ZA -> ZCE : create new FROST SigningPackage
    ZCE --> SG : send SigningPackage to all\n signing guardians participating\nof the signature.
    SG -> SG : All t participant signing guardians\nuse SigningPackage, nonces\nand KeyPackage\nto produce their signature round2.sign().
    SG --> ZCE : All t signing guardians\nsubmit their SignatureShare to ZCE\nthrough authenticated channel
    ZCE -> ZCE : Write signature Shares to a block
    ZCE -> ZCE : aggregate signatures
    ZCE -> ZCE : sign xfer
    ZCE -> ZA : return signed transaction\nsuccess or failure 
    ZA -> Z++ : Submit signed xfer to new wallet
    loop until confirmed depth reached
        ZA -> Z: Poll for block depth
        Z --> ZA--: Return depth
    end 
end 
group Finish bridge maintenance
    ZA -> ZCE++ : Wallet migration successful?\n(any Agent)
    ZCE -> PV++ : Verify
    PV --> ZCE--: Accepted/rejected
    ZCE -> ZCE: Queue bridge toll fees for\nexpiring guardians\nand certified ZavaX Agent
    ZCE -> ZCE: Update wallet address, clean up,\nand prep for next day\n(certified Agent timing list, etc.)
    ZCE -> ZCE: Write block with results
    ZCE -[#green]> ZCE: <color:green>Write block: <b>Status: Up\n<color:green>'ZavaX bridge functioning normally.'
    ZCE --> ZA --: Results
end 
@enduml
